### ISSUE TITLE
Is fast boot speed of the Linux kernel part of LinuxBoot’s agenda?

### ISSUE THREAD

**Issue by paulmenzel** [linuxboot/linuxboot#16]
[Probably, the mailing list would be the better forum, but I still do not know how to subscribe with a non Google Mail account.]

The ROM kernel should boot as quick as possible, so besides hosting configurations to build a minimal Linux kernel, patches and guides how to further speed up the boot should be collected in the LinuxBoot repository/infrastructure.

**Comment by vejmarie** [comment]
Hi Paul, you can also use slack to directly chat with the team. I am not sure that fast boot is a priority today, but clearly one of the goal of linuxboot is to enhance boot time of hardware. Now we don't compare (yet) one to build to another, but more with stock uefi. Currently the kernel starts quite fast by the way and the longest time is probably lost into pcie enumeration which I believe is not that easy to accelerate.

**Comment by rminnich** [comment]
Note that this fast boot goal does not actually match all use cases, hence it is desirable to boot as fast as possible but there are some .com's that have other needs that may slow booting down.

**Comment by orangecms** [comment]
I'm taking this as: Let's document impact on boot speed of various components and features, which may include things like initramfs compression, etc.. Even if not being everyone's goal, it's sensible to have that, I think.

**Comment by paulmenzel** [comment]
It’s probably not LinuxBoot specific enough, and some other forum should be used to document this, so all projects can profit.

Before I close this, just a note, that Amazon seems to work on this for server systems: [[PATCH 00/11] Parallel CPU bringup for x86_64](https://lore.kernel.org/lkml/20211209150938.3518-1-dwmw2@infradead.org/).
