### ISSUE TITLE
PRR, FLOCKDN, BIOS_CNTL from userspace

### ISSUE THREAD

**Issue by osresearch** [linuxboot/linuxboot#4]
Prior to `kexec`ing the user kernel, LinuxBoot boot runtime should have a way of locking down the platform configuration bits.

**Comment by osresearch** [comment]
`flashtool` can set the bits from user space: https://github.com/osresearch/flashtools

Winterfell is setting `BIOS_CNTL = SMM_BWP` in the AMI firmware. Need to find where it is set.

@dhendrix says: For Mono Lake and newer, it is controlled via the "BIOS Lock" HII setting. Not sure about Winterfell though. (i guess that's Aptio4 vs. Aptio5?)

**Comment by osresearch** [comment]
On Winterfell it is possible to prevent `SbDxe` from setting `BIOS_CNTL.SMMBWP`, either by changing a byte in the executable or possibly through settng bit 0xD in the `SbPlatformInfo` NVRAM variable.

```
 00006270: 00 49 c7 43 18 a3 00 00 00 66 89 41 1c 48 8d 44  .I.C.....f.A.H.D
 00006280: 24 50 48 8d 4c 24 30 48 89 44 24 20 48 8b 05 7d  $PH.L$0H.D$ H..}
 00006290: 6d 00 00 ff 50 48 48 b9 00 00 00 00 00 00 00 80  m...PHH.........
-000062a0: 48 85 c1 75 4a 0f ba 64 24 70 0d 73 42 41 b9 dc  H..uJ..d$p.sBA..
+000062a0: 48 85 c1 eb 4a 0f ba 64 24 70 0d 73 42 41 b9 dc  H...J..d$p.sBA..
 000062b0: 00 00 00 45 33 c0 b2 1f 33 c9 e8 09 11 00 00 41  ...E3...3......A
 000062c0: b9 dc 00 00 00 45 33 c0 0c 22 b2 1f 33 c9 88 44  .....E3.."..3..D
 000062d0: 24 20 e8 95 16 00 00 48 8b 0d 32 70 00 00 45 33  $ .....H..2p..E3
```

**Comment by kocoman2** [comment]
is there a winterfell.rom that I can download to look at ? thx
