### ISSUE TITLE
LinuxBoot: unable to load bzImage image

### ISSUE THREAD

**Issue by liunan9527** [linuxboot/linuxboot#45]
when I make run the linuxboot with qemu it cause this mistake,anyone can help me?
cut the log
----------------------------------------------------------
handle_count=00000049
LinuxBoot: bds_main dispatch
LinuxBoot: signal ready to boot
LinuxBoot: Looking for bzimage
LinuxBoot: FFS buffer=0000000006E1E018
LinuxBoot: FFS length=001E1030
LinuxBoot: unable to load bzImage image
ASSERT [DxeCore] /home/liu/work/linuxboot/edk2/MdeModulePkg/Core/Dxe/DxeMain/DxeMain.c(607): ((BOOLEAN)(0==1))
!!!! X64 Exception Type - 03(#BP - Breakpoint)  CPU Apic ID - 00000000 !!!!
RIP  - 0000000007F33EC6, CS  - 0000000000000038, RFLAGS - 0000000000000206
RAX  - 0000000000000070, RCX - 0000000007F32D00, RDX - 00000000000003F8
RBX  - 0000000007F32CA0, RSP - 0000000007F32C60, RBP - 0000000007F52C30
RSI  - 0000000007F52BA8, RDI - 0000000007918C18
R8   - 0000000007F32D10, R9  - 0000000000000000, R10 - 0000000000000070
R11  - 0000000000000000, R12 - 0000000007F52C30, R13 - 0000000007F52178
R14  - 0000000007A18230, R15 - 0000000003FDFC01
DS   - 0000000000000030, ES  - 0000000000000030, FS  - 0000000000000030
GS   - 0000000000000030, SS  - 0000000000000030
CR0  - 0000000080010033, CR2 - 0000000000000000, CR3 - 0000000007C01000
CR4  - 0000000000000668, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 0000000007BEEA98 0000000000000047, LDTR - 0000000000000000
IDTR - 00000000078FE018 0000000000000FFF,   TR - 0000000000000000
FXSAVE_STATE - 0000000007F328C0
!!!! Find image based on IP(0x7F33EC6) /home/liu/work/linuxboot/edk2/Build/MdeModule/DEBUG_GCC5/X64/MdeModulePkg/Core/Dxe/DxeMain/DEBUG/DxeCore.dll (ImageBase=0000000007F33000, EntryPoint=0000000007F39923) !!!!

**Comment by xcc-123** [comment]
I have the same problem as you，how did you solve it?
