### ISSUE TITLE
Clock issue after kexec

### ISSUE THREAD

**Issue by vejmarie** [linuxboot/linuxboot#8]
The TSC clock is not longer available after kexec. It looks like it needs to be reset. This bug doesn't seems to be specific to linuxboot, but is inducing issues with KVM later on.

This can be check with cat /sys/devices/system/clocksource/clocksource0/available_clocksource
By the way, linuxboot kernel detect properly TSC on Xeon cpus.

**Comment by osresearch** [comment]
Was this fixed by enabling ACPI?

**Comment by vejmarie** [comment]
Yes it is. We can close the issue, sorry I forgot to do it. You can force TSC by the way in the case ACPI is not available by using tsc=reliable kernel parameter.
