### ISSUE TITLE
What is the CONFIG_EFI_BDS?

### ISSUE THREAD

**Issue by jclab-joseph** [linuxboot/linuxboot#83]
I can't find anything about CONFIG_EFI_BDS in the linux kernel source. Where are you?

**Comment by rminnich** [comment]
I wonder if it was supposed to be Boot Data Services? 

oh, right, blast from the past

https://groups.google.com/g/linuxboot/c/BsCgdzdokkE

**Comment by jclab-joseph** [comment]
@rminnich Thank you!
